feat: add example with go proto codegen
This is a primary motivating use case for this ruleset.

Behavior:
Use case: developer changes foo.proto to remove a field. They either
1. don't update the foo.pb.go file in the source tree
2. they do update it but incorrectly (commonly an AI agent might do this)

Their editor doesn't show an issue, but their Bazel tests will fail.
Because we have flag //diff:validate_diffs set in bazelrc, attempting to execute a test which depends on the protobuf
file won't even build:

```
diff.bzl % bazel test examples:foo_usage_test
INFO: Analyzed target //examples:foo_usage_test (168 packages loaded, 12749 targets configured).
ERROR: /Users/alexeagle/Projects/diff.bzl/examples/BUILD:23:5: Action examples/bazel-out/darwin_arm64-fastbuild/bin/examples/go_codegen_diff.exit_code.valid failed: (Exit 1): bash failed: error executing Action command (from diff_rule rule target //examples:go_codegen_diff) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
        ERROR: diff command exited with non-zero status.

        To accept the diff, run:
        patch -d $(bazel info workspace) -p0 < $(bazel info bazel-bin)/examples/go_codegen_diff.patch

Target //examples:foo_usage_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.952s, Critical Path: 0.04s
INFO: 2 processes: 518 action cache hit, 2 internal.
ERROR: Build did NOT complete successfully
//examples:foo_usage_test                                       FAILED TO BUILD
```